// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Financial_Project
{
    public partial class Test
    {
        /// <summary>
        /// model input class for Test.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"DATE")]
            public string DATE { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"OPEN")]
            public float OPEN { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"HIGH")]
            public float HIGH { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"LOW")]
            public float LOW { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"CLOSE")]
            public float CLOSE { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Test.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"DATE")]
            public float[] DATE { get; set; }

            [ColumnName(@"OPEN")]
            public float OPEN { get; set; }

            [ColumnName(@"HIGH")]
            public float HIGH { get; set; }

            [ColumnName(@"LOW")]
            public float LOW { get; set; }

            [ColumnName(@"CLOSE")]
            public float CLOSE { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Test.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
