
// This file was auto-generated by ML.NET Model Builder. 

using XLV_Monthly_ML;

// Create single instance of sample data from first line of dataset for model input
Test.ModelInput sampleData = new Test.ModelInput()
{
    Timestamp = @"2024-12-31",
    Open = 147.32F,
    High = 147.58F,
    Low = 135.945F,
    Volume = 159105600F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Close with predicted Close from sample data...\n\n");


Console.WriteLine($"Timestamp: {@"2024-12-31"}");
Console.WriteLine($"Open: {147.32F}");
Console.WriteLine($"High: {147.58F}");
Console.WriteLine($"Low: {135.945F}");
Console.WriteLine($"Close: {137.57F}");
Console.WriteLine($"Volume: {159105600F}");


// Make a single prediction on the sample data and print results
var predictionResult = Test.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Close: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

