
// This file was auto-generated by ML.NET Model Builder. 

using XLE_Monthly_ML;

// Create single instance of sample data from first line of dataset for model input
Test.ModelInput sampleData = new Test.ModelInput()
{
    Timestamp = @"2024-12-31",
    Open = 95.5F,
    High = 95.66F,
    Low = 82.75F,
    Volume = 273774720F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Close with predicted Close from sample data...\n\n");


Console.WriteLine($"Timestamp: {@"2024-12-31"}");
Console.WriteLine($"Open: {95.5F}");
Console.WriteLine($"High: {95.66F}");
Console.WriteLine($"Low: {82.75F}");
Console.WriteLine($"Close: {85.66F}");
Console.WriteLine($"Volume: {273774720F}");


// Make a single prediction on the sample data and print results
var predictionResult = Test.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Close: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

