
// This file was auto-generated by ML.NET Model Builder. 

using XLY_Monthly_ML;

// Create single instance of sample data from first line of dataset for model input
Test.ModelInput sampleData = new Test.ModelInput()
{
    Timestamp = @"2024-12-31",
    Open = 223.87F,
    High = 240.28F,
    Low = 222.86F,
    Volume = 73590420F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Close with predicted Close from sample data...\n\n");


Console.WriteLine($"Timestamp: {@"2024-12-31"}");
Console.WriteLine($"Open: {223.87F}");
Console.WriteLine($"High: {240.28F}");
Console.WriteLine($"Low: {222.86F}");
Console.WriteLine($"Close: {224.35F}");
Console.WriteLine($"Volume: {73590420F}");


// Make a single prediction on the sample data and print results
var predictionResult = Test.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Close: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

