
// This file was auto-generated by ML.NET Model Builder. 

using XLB_Monthly_ML;

// Create single instance of sample data from first line of dataset for model input
Test.ModelInput sampleData = new Test.ModelInput()
{
    Timestamp = @"2024-12-31",
    Open = 94.88F,
    High = 95.18F,
    Low = 83.4F,
    Volume = 104278460F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Close with predicted Close from sample data...\n\n");


Console.WriteLine($"Timestamp: {@"2024-12-31"}");
Console.WriteLine($"Open: {94.88F}");
Console.WriteLine($"High: {95.18F}");
Console.WriteLine($"Low: {83.4F}");
Console.WriteLine($"Close: {84.14F}");
Console.WriteLine($"Volume: {104278460F}");


// Make a single prediction on the sample data and print results
var predictionResult = Test.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Close: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

