
// This file was auto-generated by ML.NET Model Builder. 

using XLP_Monthly_ML;

// Create single instance of sample data from first line of dataset for model input
Test.ModelInput sampleData = new Test.ModelInput()
{
    Timestamp = @"2024-12-31",
    Open = 83.14F,
    High = 83.285F,
    Low = 78.12F,
    Volume = 193146480F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Close with predicted Close from sample data...\n\n");


Console.WriteLine($"Timestamp: {@"2024-12-31"}");
Console.WriteLine($"Open: {83.14F}");
Console.WriteLine($"High: {83.285F}");
Console.WriteLine($"Low: {78.12F}");
Console.WriteLine($"Close: {78.61F}");
Console.WriteLine($"Volume: {193146480F}");


// Make a single prediction on the sample data and print results
var predictionResult = Test.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Close: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

