
// This file was auto-generated by ML.NET Model Builder. 

using XLRE_Monthly_ML;

// Create single instance of sample data from first line of dataset for model input
Test.ModelInput sampleData = new Test.ModelInput()
{
    Timestamp = @"2024-12-31",
    Open = 44.75F,
    High = 44.83F,
    Low = 39.925F,
    Volume = 107848460F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Close with predicted Close from sample data...\n\n");


Console.WriteLine($"Timestamp: {@"2024-12-31"}");
Console.WriteLine($"Open: {44.75F}");
Console.WriteLine($"High: {44.83F}");
Console.WriteLine($"Low: {39.925F}");
Console.WriteLine($"Close: {40.67F}");
Console.WriteLine($"Volume: {107848460F}");


// Make a single prediction on the sample data and print results
var predictionResult = Test.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Close: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

