
// This file was auto-generated by ML.NET Model Builder. 

using XLK_Monthly_ML;

// Create single instance of sample data from first line of dataset for model input
Test.ModelInput sampleData = new Test.ModelInput()
{
    Timestamp = @"2024-12-31",
    Open = 233.9F,
    High = 241.88F,
    Low = 230.19F,
    Volume = 95310744F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Close with predicted Close from sample data...\n\n");


Console.WriteLine($"Timestamp: {@"2024-12-31"}");
Console.WriteLine($"Open: {233.9F}");
Console.WriteLine($"High: {241.88F}");
Console.WriteLine($"Low: {230.19F}");
Console.WriteLine($"Close: {232.52F}");
Console.WriteLine($"Volume: {95310744F}");


// Make a single prediction on the sample data and print results
var predictionResult = Test.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Close: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

