
// This file was auto-generated by ML.NET Model Builder. 

using SPY_Daily_ML;

// Create single instance of sample data from first line of dataset for model input
Test.ModelInput sampleData = new Test.ModelInput()
{
    Timestamp = @"2024-12-30",
    Open = 587.89F,
    High = 591.74F,
    Low = 584.41F,
    Volume = 56578756F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Close with predicted Close from sample data...\n\n");


Console.WriteLine($"Timestamp: {@"2024-12-30"}");
Console.WriteLine($"Open: {587.89F}");
Console.WriteLine($"High: {591.74F}");
Console.WriteLine($"Low: {584.41F}");
Console.WriteLine($"Close: {588.22F}");
Console.WriteLine($"Volume: {56578756F}");


// Make a single prediction on the sample data and print results
var predictionResult = Test.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Close: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

