
// This file was auto-generated by ML.NET Model Builder. 

using XLI_Monthly_ML;

// Create single instance of sample data from first line of dataset for model input
Test.ModelInput sampleData = new Test.ModelInput()
{
    Timestamp = @"2024-12-31",
    Open = 143.9F,
    High = 144.11F,
    Low = 130.64F,
    Volume = 149679090F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Close with predicted Close from sample data...\n\n");


Console.WriteLine($"Timestamp: {@"2024-12-31"}");
Console.WriteLine($"Open: {143.9F}");
Console.WriteLine($"High: {144.11F}");
Console.WriteLine($"Low: {130.64F}");
Console.WriteLine($"Close: {131.76F}");
Console.WriteLine($"Volume: {149679090F}");


// Make a single prediction on the sample data and print results
var predictionResult = Test.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Close: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

